### ISSUE TITLE
docs: Issue in page Quick Start Guide to ScyllaDB Cloud - replace the cloud video

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb-cloud-doc-issues#3]
I would like to report an issue in page https://cloud.docs.scylladb.com/master/scylladb-quickstart/index

### Problem

Out of date video

###  Suggest a fix

Use 
https://www.youtube.com/watch?v=3Mslo3zBFQM

**Comment by annastuchlik** [comment]
The video is outdated, and I'll remove it from the quickstart guide.
The video you linked is not the best replacement to be used in the Quick Start guide because it offers a high-level overview of ScyllaDB Cloud - without actually showing the product. We can use it for now and record something else later on (for example, when Serverless is more mature).
